-- Production seed data file (empty).
--
-- All demo data has been removed via migration: 202605260001_remove_seed_demo_data.sql
-- This file is safe to run multiple times after migrations.
-- Add any required production initialization here as needed.
